// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 29/06/2025, 00.23.41
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/code/nuxt/my-portofolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/nuxt/my-portofolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/nuxt/my-portofolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/nuxt/my-portofolio/plugins/**/*.{js,ts,mjs}","D:/code/nuxt/my-portofolio/composables/**/*.{js,ts,mjs}","D:/code/nuxt/my-portofolio/utils/**/*.{js,ts,mjs}","D:/code/nuxt/my-portofolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/nuxt/my-portofolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/code/nuxt/my-portofolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/code/nuxt/my-portofolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;