// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04/07/2025, 14.36.46
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/code/nuxt/myporto/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/nuxt/myporto/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/nuxt/myporto/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/nuxt/myporto/plugins/**/*.{js,ts,mjs}","D:/code/nuxt/myporto/composables/**/*.{js,ts,mjs}","D:/code/nuxt/myporto/utils/**/*.{js,ts,mjs}","D:/code/nuxt/myporto/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/nuxt/myporto/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/code/nuxt/myporto/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/code/nuxt/myporto/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;